version: '3.8'

services:
  app:
    build: .
    container_name: graphql-back-end
    environment:
      - SERVER_PORT=8080
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    ports:
      - 8080:8080
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
